package it.localhost.trafficdroid.dao;

import it.localhost.trafficdroid.dto.StreetDTO;

import java.util.ArrayList;

public class StreetDAO {
	public static ArrayList<StreetDTO> get() {
		ArrayList<StreetDTO> streets = new ArrayList<StreetDTO>();
		StreetDTO street;
		street = new StreetDTO();
		street.setName("A1 Milano-Napoli");
		street.setCode(1);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A3 Napoli-Salerno");
		street.setCode(2);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A3 Salerno-Reggio Calabria");
		street.setCode(3);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A4 Torino-Trieste");
		street.setCode(4);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A5 Torino-Aosta");
		street.setCode(5);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A6 Torino-Savona");
		street.setCode(6);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A7 Milano-Genova");
		street.setCode(7);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A8 Autostrada dei Laghi");
		street.setCode(8);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A9 Lainate-Como-Chiasso");
		street.setCode(9);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A10 Genova-Ventimiglia");
		street.setCode(10);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A11 Firenze-Pisa");
		street.setCode(11);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A12 Genova-Rosignano");
		street.setCode(121);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A12 Roma-Civitavecchia");
		street.setCode(12);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A13 Bologna-Padova");
		street.setCode(13);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A14 Bologna-Taranto");
		street.setCode(14);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A15 Parma-La Spezia");
		street.setCode(15);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A16 Napoli-Canosa");
		street.setCode(16);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A18 Messina-Catania");
		street.setCode(18);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A19 Palermo-Catania");
		street.setCode(19);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A20 Messina-Palermo");
		street.setCode(20);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A21 Torino-Brescia");
		street.setCode(21);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A22 Brennero-Modena");
		street.setCode(22);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A23 Palmanova-Tarvisio");
		street.setCode(23);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A24 Roma-Teramo");
		street.setCode(24);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A24 A24 interna GRA");
		street.setCode(241);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A25 Torano-Pescara");
		street.setCode(25);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A26 Genova-Gravellona Toce");
		street.setCode(26);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A27 Venezia-Belluno");
		street.setCode(27);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A28 Portogruaro-Pordenone");
		street.setCode(28);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A29 Palermo-Mazzara del vallo");
		street.setCode(29);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A30 Caserta-Salerno");
		street.setCode(30);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A31 Vicenza-Thiene");
		street.setCode(31);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A32 Torino-Bardonecchia");
		street.setCode(32);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A50 Tangenziale Ovest");
		street.setCode(50);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A51 Tangenziale Est");
		street.setCode(51);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A52 Tangenziale Nord");
		street.setCode(52);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A55 Tangenziale di Torino");
		street.setCode(55);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A90 Grande Raccordo Anulare");
		street.setCode(90);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A91 Autostrada Fiumicino-Roma");
		street.setCode(91);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A1dir Dir. A1 Roma Nord");
		street.setCode(101);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A1dir Dir. A1 Roma Sud");
		street.setCode(102);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A1R Rac. A1 Bettole-Perugia");
		street.setCode(143);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A1R Rac. A1 Firenze-Siena");
		street.setCode(103);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A3R Rac. A3 Avellino-Salerno");
		street.setCode(302);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A3R Rac. A3 Sicignano-Potenza");
		street.setCode(303);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A5dir Dir. A5/A4 Ivrea");
		street.setCode(501);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A7R Rac. A7 Bereguardo-Pavia");
		street.setCode(701);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A11R Rac. A11/A12 Viareggio-Lucca");
		street.setCode(111);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A13R Rac. A13 Ferrara-P. Garibaldi");
		street.setCode(131);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A14dir Dir. A14 Ravenna");
		street.setCode(142);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A14R A14 Bologna-Casalecchio");
		street.setCode(141);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A14R Rac. A14 Ascoli Piceno");
		street.setCode(144);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A16R Rac. A16 Benevento");
		street.setCode(161);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A18T Tangenziale di Catania");
		street.setCode(181);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A21R Rac. A21/A1 Cortemaggiore");
		street.setCode(211);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A26dir A26/A4 Stroppiana-Santhia");
		street.setCode(261);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A26dir Dir. A26/A8 Cattico-Gallarate");
		street.setCode(262);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A26dir Dir. A26/A7 Predosa");
		street.setCode(263);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A29Dir Dir. A29 Alcamo-Trapani");
		street.setCode(291);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A55Dir Dir. A55 Pinerolo");
		street.setCode(552);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A55R Rac. A55 Torino-Caselle");
		street.setCode(551);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A55T Tangenziale di Torino Sud");
		street.setCode(553);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("A56 Tangenziale di Napoli");
		street.setCode(56);
		street.setActive(true);
		streets.add(street);
		street = new StreetDTO();
		street.setName("RA4 S.S. Ionica 106");
		street.setCode(301);
		street.setActive(true);
		streets.add(street);
		return streets;
	}
}
