package it.localhost.trafficdroid.common;

import java.util.HashMap;

import it.localhost.trafficdroid.R;
import android.content.Intent;

public class Const {
	public static final int[] colorCat = new int[] { 0xffffffff, 0xffff0000, 0xffff0000, 0xffff8000, 0xffffff00, 0xff47ffff, 0xff00ff00 };
	public static final int menuSettings = 1;
	public static final int menuRefresh = 2;
	public static final int notificationId = 1;
	public static final char A = 'A';
	public static final char wcm = 'A';
	public static final String openRound = " (";
	public static final String closeRound = ")";
	public static final String equal = "=";
	public static final String separator = "; ";
	public static final String domain = "; domain=";
	public static final String http = "http://";
	public static final String dyn = "/dyn/";
	public static final String html = ".html?ts=1";
	public static final String popupTelecamera = "/autostrade-mobile/popupTelecamera.do?tlc=";
	public static final String events = "/portale/rss?rsstype=traffic";
	public static final String cookie = "/autostrade/traffico.do";
	public static final String codeDiv = "div";
	public static final String codeId = "id";
	public static final String codeTable = "table";
	public static final String codeSection = "section";
	public static final String codeRoadbox = "roadbox";
	public static final String codeClass = "class";
	public static final String tdData = "trafficData";
	public static final String doUpdate = "it.localhost.trafficdroid.DO_UPDATE";
	public static final String beginUpdate = "it.localhost.trafficdroid.BEGIN_UPDATE";
	public static final String endUpdate = "it.localhost.trafficdroid.END_UPDATE";
	public static final String scheduleService = "it.localhost.trafficdroid.SCHEDULE_SERVICE";
	public static final String wakeLock = "it.localhost.trafficdroid.WAKELOCK";
	public static final Intent doUpdateIntent = new Intent(Const.doUpdate);
	public static final Intent beginUpdateIntent = new Intent(Const.beginUpdate);
	public static final Intent endUpdateIntent = new Intent(Const.endUpdate);
	public static final Intent scheduleServiceIntent = new Intent(Const.scheduleService);
	public static final String camId = "camId";
	public static final String formatDateEventi = "yyyy-MM-dd'T'HH:mm:ss'Z'";
	public static final String adMobId = "a14d8f6a3c4c2f3";
	public static final String anlyticsId = "UA-12243941-5";
	public static final String item = "item";
	public static final int[] streetsRes = new int[] { R.array.streetsId, R.array.streetsName, R.array.streetsFather };

	public static final Integer zonesRes(int key) {
		HashMap<Integer, Integer> map = new HashMap<Integer, Integer>(128);
		map.put(1, R.array.zones1Id);
		map.put(2, R.array.zones2Id);
		map.put(3, R.array.zones3Id);
		map.put(4, R.array.zones4Id);
		map.put(5, R.array.zones5Id);
		map.put(6, R.array.zones6Id);
		map.put(7, R.array.zones7Id);
		map.put(8, R.array.zones8Id);
		map.put(9, R.array.zones9Id);
		map.put(10, R.array.zones10Id);
		map.put(11, R.array.zones11Id);
		map.put(12, R.array.zones12Id);
		map.put(13, R.array.zones13Id);
		map.put(14, R.array.zones14Id);
		map.put(15, R.array.zones15Id);
		map.put(16, R.array.zones16Id);
		map.put(18, R.array.zones18Id);
		map.put(19, R.array.zones19Id);
		map.put(20, R.array.zones20Id);
		map.put(21, R.array.zones21Id);
		map.put(22, R.array.zones22Id);
		map.put(23, R.array.zones23Id);
		map.put(24, R.array.zones24Id);
		map.put(25, R.array.zones25Id);
		map.put(26, R.array.zones26Id);
		map.put(27, R.array.zones27Id);
		map.put(28, R.array.zones28Id);
		map.put(29, R.array.zones29Id);
		map.put(30, R.array.zones30Id);
		map.put(31, R.array.zones31Id);
		map.put(32, R.array.zones32Id);
		map.put(50, R.array.zones50Id);
		map.put(51, R.array.zones51Id);
		map.put(52, R.array.zones52Id);
		map.put(55, R.array.zones55Id);
		map.put(56, R.array.zones56Id);
		map.put(90, R.array.zones90Id);
		map.put(91, R.array.zones91Id);
		map.put(101, R.array.zones101Id);
		map.put(102, R.array.zones102Id);
		map.put(103, R.array.zones103Id);
		map.put(111, R.array.zones111Id);
		map.put(121, R.array.zones121Id);
		map.put(131, R.array.zones131Id);
		map.put(141, R.array.zones141Id);
		map.put(142, R.array.zones142Id);
		map.put(143, R.array.zones143Id);
		map.put(144, R.array.zones144Id);
		map.put(161, R.array.zones161Id);
		map.put(181, R.array.zones181Id);
		map.put(211, R.array.zones211Id);
		map.put(241, R.array.zones241Id);
		map.put(261, R.array.zones261Id);
		map.put(262, R.array.zones262Id);
		map.put(263, R.array.zones263Id);
		map.put(291, R.array.zones291Id);
		map.put(301, R.array.zones301Id);
		map.put(302, R.array.zones302Id);
		map.put(303, R.array.zones303Id);
		map.put(501, R.array.zones501Id);
		map.put(551, R.array.zones551Id);
		map.put(552, R.array.zones552Id);
		map.put(553, R.array.zones553Id);
		map.put(701, R.array.zones701Id);
		map.put(-1, R.array.zones1Name);
		map.put(-2, R.array.zones2Name);
		map.put(-3, R.array.zones3Name);
		map.put(-4, R.array.zones4Name);
		map.put(-5, R.array.zones5Name);
		map.put(-6, R.array.zones6Name);
		map.put(-7, R.array.zones7Name);
		map.put(-8, R.array.zones8Name);
		map.put(-9, R.array.zones9Name);
		map.put(-10, R.array.zones10Name);
		map.put(-11, R.array.zones11Name);
		map.put(-12, R.array.zones12Name);
		map.put(-13, R.array.zones13Name);
		map.put(-14, R.array.zones14Name);
		map.put(-15, R.array.zones15Name);
		map.put(-16, R.array.zones16Name);
		map.put(-18, R.array.zones18Name);
		map.put(-19, R.array.zones19Name);
		map.put(-20, R.array.zones20Name);
		map.put(-21, R.array.zones21Name);
		map.put(-22, R.array.zones22Name);
		map.put(-23, R.array.zones23Name);
		map.put(-24, R.array.zones24Name);
		map.put(-25, R.array.zones25Name);
		map.put(-26, R.array.zones26Name);
		map.put(-27, R.array.zones27Name);
		map.put(-28, R.array.zones28Name);
		map.put(-29, R.array.zones29Name);
		map.put(-30, R.array.zones30Name);
		map.put(-31, R.array.zones31Name);
		map.put(-32, R.array.zones32Name);
		map.put(-50, R.array.zones50Name);
		map.put(-51, R.array.zones51Name);
		map.put(-52, R.array.zones52Name);
		map.put(-55, R.array.zones55Name);
		map.put(-56, R.array.zones56Name);
		map.put(-90, R.array.zones90Name);
		map.put(-91, R.array.zones91Name);
		map.put(-101, R.array.zones101Name);
		map.put(-102, R.array.zones102Name);
		map.put(-103, R.array.zones103Name);
		map.put(-111, R.array.zones111Name);
		map.put(-121, R.array.zones121Name);
		map.put(-131, R.array.zones131Name);
		map.put(-141, R.array.zones141Name);
		map.put(-142, R.array.zones142Name);
		map.put(-143, R.array.zones143Name);
		map.put(-144, R.array.zones144Name);
		map.put(-161, R.array.zones161Name);
		map.put(-181, R.array.zones181Name);
		map.put(-211, R.array.zones211Name);
		map.put(-241, R.array.zones241Name);
		map.put(-261, R.array.zones261Name);
		map.put(-262, R.array.zones262Name);
		map.put(-263, R.array.zones263Name);
		map.put(-291, R.array.zones291Name);
		map.put(-301, R.array.zones301Name);
		map.put(-302, R.array.zones302Name);
		map.put(-303, R.array.zones303Name);
		map.put(-501, R.array.zones501Name);
		map.put(-551, R.array.zones551Name);
		map.put(-552, R.array.zones552Name);
		map.put(-553, R.array.zones553Name);
		map.put(-701, R.array.zones701Name);
		return map.get(key);
	}
}